version: '3.8'
services:
  php:
    container_name: spa-blade-php
    build: ./docker/php
    volumes:
      - ./:/var/www/html
  nginx:
    container_name: spa-blade-nginx
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www/html
    depends_on:
    - php
  
  db:
    container_name: spa-blade-db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel-db
      MYSQL_USER: docker
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306

  phpmyadmin:
    container_name: spa-blade-phpmyadmin
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      #- PMA_USER=user
      #- PMA_PASSWORD=password
    ports:
      - "8000:80"
    volumes:
      - ./docker/phpmyadmin/sessions:/sessions
